// category
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";

// product
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_SALE = "GET_ALL_PRODUCT_SALE";
export const GET_NEW_PRODUCT = "GET_NEW_PRODUCT";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const GET_PRODUCT_CATE = "GET_PRODUCT_CATE";
export const GET_PRODUCT_SEARCH = "GET_PRODUCT_SEARCH";
export const GET_ALL_ATTRIBUTE_SAGA = "GET_ALL_ATTRIBUTE_SAGA";
export const CREATE_PRODUCT_SAGA = "CREATE_PRODUCT_SAGA";

//user
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_ADMIN_SAGA = "LOGIN_ADMIN_SAGA";
export const REGISTER_USER = "REGISTER_USER";
export const USER_INFO_SAGA = "USER_INFO_SAGA";

//order detail
export const ORDER_DETAIL_SAGA = "ORDER_DETAIL_SAGA";
export const GET_ORDER_DETAIL_SAGA = "GET_ORDER_DETAIL_SAGA";
export const DELETE_ORDER_DETAIL_SAGA = "DELETE_ORDER_DETAIL_SAGA";
export const GET_ALL_ORDER_MANAGER_SAGA = "GET_ALL_ORDER_MANAGER_SAGA";
export const UPDATE_RATING_SAGA = "UPDATE_RATING_SAGA";

//color
export const GET_ALL_COLOR_SAGA = "GET_ALL_COLOR_SAGA";

//size
export const GET_ALL_SIZE_SAGA = "GET_ALL_SIZE_SAGA";

//brand
export const GET_ALL_BRAND_SAGA = "GET_ALL_BRAND_SAGA";

//order
export const CREATE_ORDER_PRODUCT_SAGA = "CREATE_ORDER_PRODUCT_SAGA";
